### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by makrosloro** [Youngestdev/fastapi-beanie#2]
I am following your great tutorial but when launching python app/main.py you are having an issue:

```
Python/fastapi-beanie-main/app/server/app.py", line 3, in <module>
    from app.server.database import init_db
ModuleNotFoundError: No module named 'app'
```

same issue downloading this repo and executing

**Comment by makrosloro** [comment]
Sorry, missed `export PYTHONPATH=$PWD` and add `pymongo[srv]` on requirements.txt

**Comment by Youngestdev** [comment]
Ah, glad you got it solved!
